FROM python:3.8-slim

COPY python/* /process_data/

COPY requirements_process_data.txt /tmp

RUN pip3 install -r /tmp/requirements_process_data.txt

RUN apt update
RUN apt install vim -y

WORKDIR /process_data

#CMD ["python3", "process_data.py"]
CMD  tail -f /dev/null 