FROM python:3.8-slim

COPY . /app/

COPY requirements_app.txt /tmp

RUN apt update
RUN apt install vim -y
RUN apt install gcc -y

RUN pip3 install -r /tmp/requirements_app.txt

#EXPOSE 8050
CMD gunicorn --bind 0.0.0.0:$PORT wsgi

WORKDIR /app

CMD ["python3", "app5.py"]
#CMD  tail -f /dev/null 
