daily_template = (''
' <!DOCTYPE html>'
'<html lang="en">'
'<head>'
  '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'
  '<meta name="viewport" content="width=device-width, initial-scale=1">'
  '<meta http-equiv="X-UA-Compatible" content="IE=edge">'

  '<title>BLM Tracker Daily Summary - {date}</title>'
  
'</head>'
'<body style="margin:0; padding:0; background-color:#F2F2F2;">'
  '<center>'
    '<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#F2F2F2">'
      '<tr>'
            '<td align="left" valign="top">'
              '{note}:'
            '</td>'
      '</tr>'
      '<tr>'
            '<td align="center" valign="top">'
              '<h1> Daily Summary for {date}:'
            '</td>'
      '</tr>'
      '<tr>'
            '<td align="center" valign="top">'
                '<h4>Dashboard</h4>'
                '<center><a href="{url_dashboard}" target="_blank"><img src="{url_dashboard}/.png" width="700px"></a><br><br>'
                  '<a href="{url_dashboard}/" style="color:#787a7a; text-decoration: none; font-weight: 200;" target="_blank">'
                  'Click to see the interactive graph</a><br></center><hr>'
            '</td>'
        '</tr>'
        '<tr>'
            '<td align="center" valign="top">'
                      '<h4>Top Tweets</h4>'
            '{html_top_tweets}'
            '</td>'
        '</tr>'
        '<tr>'
            '<td align="center" valign="top">'
               '<h4>Top Influencers</h4>'
                '<a href="{url_top_users}" target="_blank"><img src="{url_top_users}/.png" width="700px"></a><br><br>'
                  '<a href="{url_top_users}/" style="color:#787a7a; text-decoration: none; font-weight: 200;" target="_blank">'
                  'Click to see the interactive graph</a><br><hr>'
            '</td>'
        '</tr>'
    '</table>'
 '</center>'
'<p style="color:#787a7a">More more details, visit <a href=https://blm-tracker-app.herokuapp.com/>BLM Tracker</a>.</p>'
'<p style="color:#787a7a">If you no longer wish to receive daily emails, please <a href=api_link>un-subscribe</a> by re-entering your email address.</p>'
'</body>'
'</html>'         
'')
